version: "3.8"
services:
    loggingserver:
        context: .
        dockerfile: Dockerfile
        container_name: loggingserver
        restart: unless-stopped
        ports:
            - "3000:3000/tcp"
