version: "3.8"
services:
  loggingserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loggingserver
    restart: unless-stopped
    ports:
      - "3001:3000/tcp"
    healthcheck:
      test:
        - CMD-SHELL
        - 'exit 0'
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s